# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "debian", primary: true do |debian|
    debian.vm.box = "ARTACK/debian-jessie"
    debian.vm.hostname = "projects"
    debian.vm.network "forwarded_port", guest: 22, host: 25102, id: "ssh"
    debian.vm.network "private_network", ip: "10.0.5.102"
  
#    debian.proxy.http     = "http://proxy.mms-dresden.de:8080"
#    debian.proxy.https    = "http://proxy.mms-dresden.de:8080"
#    debian.proxy.no_proxy = "localhost,127.0.0.1"
  
    debian.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  
    debian.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natsettings1", "1500,64,64,64,1024"]
    end
  end
end